# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kEoIae45txBA54O5SpLEFkhki_QRlhAo
"""

varibalex = 11
variableY=9
VariableQ=4

# Example of three variables with different prices
item1_price = 10
item2_price = 25
item3_price = 5

# You can then perform operations using these variables. For example:
total_price = item1_price + item2_price + item3_price
print(f"The total price is: {total_price}")

total_budget = 10 + 25 + 5
# or
# total_budget = 40

# calculate the total cost of items
items = 10 + 25 + 5
total_cost = items
print(total_cost)

# Assuming total_cost and total_budget are defined variables
# Example comparison:
if total_cost > total_budget:
    print("Total cost exceeds total budget.")
elif total_cost < total_budget:
    print("Total cost is less than total budget.")
else:
    print("Total cost equals total budget.")

compare the total_cost and total_budget variables
if total_cost > total_budget:
    print("Total cost exceeds total budget.")
elif total_cost < total_budget:
    print("Total cost is less than total budget.")
else:
    print("Total cost equals total budget.")
elif total_cost < total_budget:
    print("Total cost is less than total budget.")
else:
    print("Total cost equals total budget.")
elif total_cost < total_budget:
    print("Total cost is less than total budget.")
else:
    print("Total cost equals total budget.")
elif total_cost < total_budget:
    print("Total cost is less than total budget.")
else:
    print("Total cost equals total budget.")

# This is not code, so there's nothing to correct.
# To calculate the difference, you'll need to provide the relevant amounts.
# For example:

amount_available = 100
amount_needed = 150

difference = amount_needed - amount_available

if difference > 0:
    print(f"You need ${difference} more.")
else:
    print(f"You have ${-difference} left over.")